# Generated by Django 3.1.2 on 2020-11-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='des',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='music',
            name='mix_mastering',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
