# Generated by Django 3.1.2 on 2020-11-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20201120_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='label',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=' لیبل'),
        ),
        migrations.AddField(
            model_name='music',
            name='label',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=' لیبل'),
        ),
    ]
